apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    containers:
      - name: aws-secret-sidecar
        image: chlam4/chris-poc-sidecar:v3
        imagePullPolicy: Always
        volumeMounts:
          - name: secrets
            mountPath: /data
    volumes:
      - name: secrets
        emptyDir:
          medium: Memory
